Develop
mate-academy/ts_sort_students pull request #1128
Opened 2023-03-05 11:23 UTC by Zelinskyi-Serhii

2023-03-05 14:29 UTC, vladyslav-mosor requested changes
Cheklist p.3. Try to rewrite your switch-case construction so you cas use the same logic for sorting by name or surname (because they both have the type string so you dont have to repeat your code). The same for sorting by age and married.

+ if you use return inside switch construction it`s not necessary to use break.

2023-03-05 14:29 UTC, vladyslav-mosor commented on src/sortStudents.ts
> +      break;
You could use the same logic as for sorting by number type instead of this. Because your boolean values could be converted to number values.

2023-03-05 14:29 UTC, vladyslav-mosor commented on src/sortStudents.ts
> +      break;
Try to create a helper function for calculating average grade so you dont have to repeat your code.

2023-03-08 08:58 UTC, sergii-nosachenko requested changes

2023-03-08 08:58 UTC, sergii-nosachenko commented on src/sortStudents.ts
> +export type SortOrder = 'asc' |'desc';
```suggestion
export type SortOrder = 'asc' | 'desc';
```

2023-03-08 08:58 UTC, sergii-nosachenko commented on src/sortStudents.ts
> +function countSum(numbers: number[]): number {
Better refactor this helper function to calculate the average value.

2023-03-08 08:58 UTC, sergii-nosachenko commented on src/sortStudents.ts
> +  const copyObject = copyArray.map((person) => ({ ...person }));
You don't need to make a deep copy of the array. You are changing only the order of objects, objects themselves are staying untouched.

2023-03-08 08:58 UTC, sergii-nosachenko commented on src/sortStudents.ts
> +          : current[sortBy].localeCompare(prev[sortBy]);
DRY: you don't need to have both comparisons. Just make one and multiply the result by -1 in the case of `desc` order.
Fix it everywhere.

2023-03-08 08:58 UTC, sergii-nosachenko commented on src/sortStudents.ts
> +      copyObject.sort((prev, current) => {
```suggestion
      return copyObject.sort((prev, current) => {
```
You can return a result immediately.

2023-03-08 08:58 UTC, sergii-nosachenko commented on src/sortStudents.ts
> +      throw new Error('wrong parameters');
Provide detailed message. Use template string to show faulty `sortBy` value.

2023-03-09 16:06 UTC, OleksiiBlezniuk requested changes
Let's simplify your code

2023-03-09 16:06 UTC, OleksiiBlezniuk commented on src/sortStudents.ts
> +          : compare * -1;
Looks like this multiplier can be moved to constant, it's same for all cases

2023-03-10 08:10 UTC, sergii-nosachenko requested changes

2023-03-10 08:10 UTC, sergii-nosachenko commented on src/sortStudents.ts
> +  const adscCompare = -1;
```suggestion
  const direction = order === 'asc' ? 1 : -1;
```

2023-03-10 08:10 UTC, sergii-nosachenko commented on src/sortStudents.ts
> +          : compare * adscCompare;
You can immediately return a result from callback multiplied by `direction`.

2023-03-10 08:10 UTC, sergii-nosachenko commented on src/sortStudents.ts
> +      throw new Error('Wrong sort type parameters');
Be more specific: use template string and sortBy value.

2023-03-10 10:36 UTC, sergii-nosachenko approved these changes
Good work 👍

2023-07-12 20:02 UTC, closed without merging