add sortStudents solution
mate-academy/ts_sort_students pull request #1336
Opened 2023-05-16 12:04 UTC by DidenkoDenis306

2023-05-17 06:46 UTC, dinaminahi requested changes

2023-05-17 06:46 UTC, dinaminahi commented on src/sortStudents.ts
> +  const studentsCopy: Student[] = [...students];
You can omit `Student[]` typing since typescript can handle it, because you already give the type for `students`

2023-05-17 06:46 UTC, dinaminahi commented on src/sortStudents.ts
> +    return studentsCopy.sort((student1: Student, student2: Student) => (
Same here, you don't really have to specify the type for `student1` and `student2`, typescript will know it by itself, because you are sorting `studentsCopy` which is `Student` array.

In practice you should specify the type when:

- When you declare a variable and assign it a value later.
- When you want a variable that can’t be inferred.
- When a function returns the `any` type and you need to clarify the value.

2023-05-17 06:46 UTC, dinaminahi commented on src/sortStudents.ts
> +function getAverageGrade(grades: number[]): number {
Same here about  type that function return
https://www.typescripttutorial.net/typescript-tutorial/typescript-type-inference/

2023-05-18 11:07 UTC, DidenkoDenis306 commented on src/sortStudents.ts
> +function getAverageGrade(grades: number[]): number {
I know this, but linter forces me to write the return type of the function, otherwise it writes an error

2023-05-19 06:20 UTC, dinaminahi approved these changes
Well done 🥇

2023-05-19 06:20 UTC, dinaminahi commented on src/sortStudents.ts
> +function getAverageGrade(grades: number[]): number {
Okay, my fault, sorry

2024-07-09 10:16 UTC, closed without merging