Solution
mate-academy/ts_sort_students pull request #1570
Opened 2023-08-11 12:58 UTC by klaudia-klis

2023-08-11 17:51 UTC, asakevych requested changes
Great job!! 🚀 
I think your solution can be even better if you use switch and group your functions: 
```
case SortType.Name:
case SortType.Surname:
   return (order === 'asc')
      ? copyOfStudents.sort((a, b) => a[sortBy].localeCompare(b[sortBy]))
      : copyOfStudents.sort((a, b) => b[sortBy].localeCompare(a[sortBy]));
```
you can also create some function like `calculateAvarage` not to repeat same logic twice

2023-08-16 07:11 UTC, choeqq requested changes
Logic looks really good, I think you could just clean up your code, with function for picking values, instead of using sort method 10 times 🚀

2023-08-16 07:11 UTC, choeqq commented on src/sortStudents.ts
> +  }
try to use sort method only once, you can have separate function for picking values to sort, only then pass them to sort method

2023-08-16 11:18 UTC, closed without merging

2023-08-16 13:03 UTC, mvjl000 approved these changes
Well done! 🚀