solved sorter
mate-academy/ts_sort_students pull request #361
Opened 2022-03-11 14:06 UTC by krolich500grn

2022-03-14 12:19 UTC, solaryasha requested changes

2022-03-14 12:19 UTC, solaryasha commented on src/sortStudents.ts
> +      ) / b.grades.length;
Дублюєш код, давай уникнемо цього

2022-03-14 12:19 UTC, solaryasha commented on src/sortStudents.ts
> +          throw new Error('Error :3');
Краще вже 0 повертай

2022-03-14 12:19 UTC, solaryasha commented on src/sortStudents.ts
> +      }
Це костиль, ти можеш це зробити одразу ж, просто переставити `a` i `b`

2022-03-14 14:49 UTC, krolich500grn commented on src/sortStudents.ts
> +      }
@solaryasha Assignment to function parameter 'a'. [no-param-reassign]

2022-03-15 10:55 UTC, solaryasha approved these changes

2022-03-15 10:55 UTC, solaryasha commented on src/sortStudents.ts
> +      };
Винеси цю функцію з тіла функції sortStudents

2022-03-15 10:55 UTC, solaryasha commented on src/sortStudents.ts
> +      const averageGrades = (grades: number[]): number => {
```suggestion
      const calculateAverageGrades = (grades: number[]): number => {
```

2022-03-15 11:28 UTC, krolich500grn commented on src/sortStudents.ts
> +      };
done

2022-07-21 13:39 UTC, closed without merging