Sort students
mate-academy/ts_sort_students pull request #364
Opened 2022-03-17 14:50 UTC by max-shlikhta

2022-03-18 11:30 UTC, solaryasha requested changes

2022-03-18 11:30 UTC, solaryasha commented on src/sortStudents.ts
> +    result = grades.reduce((prev, curr) => prev + curr, 0) / grades.length;
```suggestion
    return grades.reduce((prev, curr) => prev + curr, 0) / grades.length;
```

2022-03-18 11:30 UTC, solaryasha commented on src/sortStudents.ts
> +
Щоб не дублювати код тричі міг би переставити значення наступним чином:
```
const currentStudent = order !== 'asc'  ? nextStudent: currentStudent
const nextStudent = order !== 'asc'  ? currentStudent: nextStudent

2022-03-22 09:04 UTC, Ihor-Karpyn approved these changes

2025-08-31 10:27 UTC, closed without merging