solution
mate-academy/ts_sort_students pull request #438
Opened 2022-05-19 19:14 UTC by lytvyshko

2022-05-20 10:55 UTC, AndriiRut requested changes
Good Job! (=

2022-05-20 10:55 UTC, AndriiRut commented on src/sortStudents.ts
> +  const studentsCopy = students.slice();
You can use `Spread operator` to make a copy of `objects` or `arrays`

2022-05-20 13:04 UTC, Anna-Tkachenko requested changes

2022-05-20 13:04 UTC, Anna-Tkachenko commented on src/sortStudents.ts
> +  if (sortBy === SortType.Name || sortBy === SortType.Surname) {
Check point 1 in checklist

2022-05-20 13:59 UTC, Anna-Tkachenko approved these changes

2022-05-20 13:59 UTC, Anna-Tkachenko commented on src/sortStudents.ts
> +        ? studentsCopy.sort((a, b) => +a[sortBy] - +b[sortBy])
Will be better to move all logic inside the sort method
And use default case for unexpected initial values or for throwing erros
This logic should be for 'born' and 'died' fields

2022-05-20 14:25 UTC, lytvyshko commented on src/sortStudents.ts
> +        ? studentsCopy.sort((a, b) => +a[sortBy] - +b[sortBy])
Have I understood you right?

2022-05-21 13:16 UTC, Anna-Tkachenko approved these changes

2022-05-21 13:16 UTC, Anna-Tkachenko commented on src/sortStudents.ts
> +      return studentsCopy.sort((a, b) => {
Will be better to write all logic inside method sort
If you'll want to change variable name for students array or change some variables inside method sort you should do it 3 times in your code

2024-04-01 08:40 UTC, closed without merging