lets see
mate-academy/ts_sort_students pull request #546
Opened 2022-07-01 11:41 UTC by Havrysh

Pls leave a bit more specific comment on my mistakes so i can fix it with deeper understanding, tnx

2022-07-02 12:14 UTC, Bohdan-Maksymiuk requested changes

2022-07-02 12:14 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +// eslint-disable-next-line max-len
do not reset eslint rules

2022-07-02 12:14 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +export function sortStudents(students: Student, sortBy: SortType, order: SortOrder): [] {
```suggestion
export function sortStudents(
  students: Student,
  sortBy: SortType,
  order: SortOrder,
): Student[] {
```

2022-07-02 12:14 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +      case SortType.Name || SortType.Surname:
```suggestion
      case SortType.Name:
      case SortType.Surname:
```
better use such syntax

2022-07-02 12:14 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +        return students.slice().sort((x, y) =>
```suggestion
        return [...students].sort((x, y) =>
```
better make copy in such way

2022-07-02 12:14 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +        return students.slice().sort((x, y) =>
and `student1`, `student2` instead of x and y

2022-07-02 13:22 UTC, Bohdan-Maksymiuk requested changes

2022-07-02 13:22 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +    }
it is not default, what if we add some new sortBy, or someone make a typo in sortBy string?

2022-07-02 13:22 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +        return order === 'asc'
```suggestion
        return order === SortOrder.Asc
```

2022-07-02 13:22 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +        return order === 'asc'
.

2022-07-02 13:22 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +        return order === 'asc'
.

2022-07-02 13:22 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +  desc = 'desc',
```suggestion
  Asc = 'asc',
  Desc = 'desc',
```
capitalize for enum names

2022-07-02 13:22 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +    }
this comment not fixed

2022-07-05 07:22 UTC, marina-tilniak requested changes

2022-07-05 07:22 UTC, marina-tilniak commented on src/sortStudents.ts
> +          ? student1.sortBy.reduce((sum, t) => sum + t, 0)
тут треба знайти середнє,а не суму

2022-07-05 07:22 UTC, marina-tilniak commented on src/sortStudents.ts
> +          ? student1.sortBy.reduce((sum, t) => sum + t, 0)
student1.sortBy - такий запис не скомпілюється. У студента немає властивлсті sortBy

2022-07-05 07:22 UTC, marina-tilniak commented on src/sortStudents.ts
> +  students: Student,
```suggestion
  students: Student[],
```

2024-12-11 13:29 UTC, closed without merging