Sort Students v1
mate-academy/ts_sort_students pull request #59
Opened 2021-08-18 06:24 UTC by ivan-major

2021-08-18 12:50 UTC, mykola-yarchuk submitted a review, later dismissed
test

2021-08-19 14:29 UTC, vkryvytskyy requested changes

2021-08-19 14:29 UTC, vkryvytskyy commented on src/sortStudents.ts
> +      }
Это абсолютно одинаковый код только во втором случае ты делаешь b-a, а не a-b, уверен это можно унифицировать

2021-08-21 11:47 UTC, vkryvytskyy approved these changes

2021-08-21 11:47 UTC, vkryvytskyy commented on src/sortStudents.ts
> +      const callback = (sum: number, x: number) => sum + x;
Эту функцию можно создать вне switch..case, чтобы она не пересоздавалась каждый раз

2025-01-26 13:16 UTC, closed without merging