Task is done
mate-academy/ts_sort_students pull request #623
Opened 2022-08-17 18:54 UTC by Konsttantin

2022-08-20 11:02 UTC, marina-tilniak requested changes

2022-08-20 11:02 UTC, marina-tilniak commented on src/sortStudents.ts
не виключай лінтер, перенеси код на наступний рядок

2022-08-20 11:02 UTC, marina-tilniak commented on src/sortStudents.ts
> +      return order === 'asc' ? (aAverage - bAverage) : (bAverage - aAverage);
```suggestion
      return order === 'asc'
        ? (aAverage - bAverage)
        : (bAverage - aAverage);
```

2022-08-20 11:02 UTC, marina-tilniak commented on src/sortStudents.ts
> +  });
тут теж перенеси

2022-08-25 15:48 UTC, Bohdan-Maksymiuk approved these changes

2022-08-25 15:48 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +      return order === 'asc' ? (aAverage - bAverage) : (bAverage - aAverage);
fix code style as Marina asked

2025-01-19 15:39 UTC, closed without merging