develop
mate-academy/ts_sort_students pull request #802
Opened 2022-10-15 23:02 UTC by savchuksavchuk

2022-10-18 10:04 UTC, Bohdan-Maksymiuk requested changes

2022-10-18 10:04 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +        .reduce((x: number, y: number): number => x + y) / a[sortBy].length;
pass this logic into separate function and reuse it

2022-10-18 10:04 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +      const first: number = a[sortBy]
use switch for such predefined cases

2022-10-18 10:04 UTC, Bohdan-Maksymiuk commented on src/sortStudents.ts
> +  result.sort((a: Student, b: Student): number => {
```suggestion
  return [...students].sort((a: Student, b: Student): number => {
```
you may just return it

2022-10-24 14:53 UTC, liliia-livandovskaya requested changes
GJ! 👍  Pay attention to comments

2022-11-02 17:36 UTC, polosanya approved these changes
Well done!

2024-12-28 11:12 UTC, closed without merging