solution
mate-academy/ts_sort_students pull request #925
Opened 2022-12-16 21:26 UTC by illiashcherbak

2022-12-19 15:50 UTC, anastasiia-bilska requested changes
Good! Please, check my comments

2022-12-19 15:50 UTC, anastasiia-bilska commented on src/sortStudents.ts
> +      break;
```suggestion
  const sortedStudentsList = [...students];

  switch (sortBy) {
    case SortType.Name:
    case SortType.Surname:
      return sortedStudentsList
        .sort((currStudent, nextStudent) => {
          return order === 'asc'
            ? currStudent[sortBy].localeCompare(nextStudent[sortBy])
            : nextStudent[sortBy].localeCompare(currStudent[sortBy]);
        });
```

2022-12-19 15:50 UTC, anastasiia-bilska commented on src/sortStudents.ts
> +      break;
sort is a mutable, you don't need to assign the result and you can use const for sortedStudentsList. You also can return sorted list, so you don't need to write 'break'. Same for next cases

2022-12-19 15:50 UTC, anastasiia-bilska commented on src/sortStudents.ts
>  }
```suggestion
    default:
       return sortedStudentsList;  
    }
}
```

2022-12-20 07:35 UTC, anastasiia-bilska approved these changes
Well done!

2022-12-20 07:40 UTC, solaryasha approved these changes

2022-12-20 07:40 UTC, solaryasha commented on src/sortStudents.ts
> +  return avarageAge;
```suggestion
  return sumOfGrades / gradesArray.length;;
```

2022-12-20 07:40 UTC, solaryasha commented on src/sortStudents.ts
> +  const sortedStudentsList = [...students];
```suggestion
  const copiedStudents = [...students];
```

2024-03-11 16:55 UTC, closed without merging